### ISSUE TITLE
Request to Release All 13,020 Entity Types Used in the Model

### ISSUE THREAD

**Issue by EagleW** [universal-ner/universal-ner#10]
Hello, 

Thank you for providing such a valuable tool. I'm interested in knowing if there are plans to release all 13,020 entity types used in the model in the future. It would greatly enhance its utility for our needs.

Thank you again for your assistance and hard work.

**Comment by wzhouad** [comment]
We have released the pretrain data of both entity types and definitions at [Huggingface](https://huggingface.co/Universal-NER). You may extract entity types from it.

**Comment by EagleW** [comment]
Thank you very much!
