### ISSUE TITLE
[Question] prompt UniversalNER with multiple entity types?

### ISSUE THREAD

**Issue by yiling-chen** [universal-ner/universal-ner#2]
Hi,

Thanks for the awesome work. I am curious about if there is a way to prompt the model with multiple entity types?

Thank you.

**Comment by wzhouad** [comment]
As outlined in our paper, we tackle multiple entity types by individually feeding each type to the model.

**Comment by yiling-chen** [comment]
Could you please share a more complete list of the entity types contained in the ChatGPT generated data used to train your model. It will be very helpful when testing the model. Thanks.
