### ISSUE TITLE
How to use from the transformers library

### ISSUE THREAD

**Issue by AleksandrTulenkov** [universal-ner/universal-ner#4]
Hi!
Awesome job!

I have a question how to use it from the transformers library:
```
from transformers import pipeline

pipe = pipeline("text-generation", model="Universal-NER/UniNER-7B-definition")
```
this one doesn't work for me

**Comment by AndreaLombax** [comment]
I tried this way, and it worked:

```
model_path = 'Universal-NER/UniNER-7B-type'
#model_path = 'Universal-NER/UniNER-7B-all'
tokenizer = AutoTokenizer.from_pretrained(model_path)

pipeline = transformers.pipeline(
    "text-generation", 
    model=model_path,
    tokenizer=tokenizer,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    max_length=1000,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

```

The tokenizer should be initialized before passing it to the pipeline.

**Comment by AleksandrTulenkov** [comment]
> I tried this way, and it worked:
> 
> ```
> model_path = 'Universal-NER/UniNER-7B-type'
> #model_path = 'Universal-NER/UniNER-7B-all'
> tokenizer = AutoTokenizer.from_pretrained(model_path)
> 
> pipeline = transformers.pipeline(
>     "text-generation", 
>     model=model_path,
>     tokenizer=tokenizer,
>     trust_remote_code=True,
>     device_map="auto",
>     torch_dtype=torch.bfloat16,
>     max_length=1000,
>     do_sample=True,
>     top_k=10,
>     num_return_sequences=1,
>     eos_token_id=tokenizer.eos_token_id,
> )
> ```
> 
> The tokenizer should be initialized before passing it to the pipeline.

Thanks! But when I'm trying to pipeline("prompt") it just returns original text, should some specific prompt be used?

**Comment by polodealvarado** [comment]
Hi @AleksandrTulenkov .
You should use the prompt described in the[ HF model card (template)](https://huggingface.co/Universal-NER/UniNER-7B-definition).

On the other hand, I have tried it with your description @AndreaLombax and it worked for me but the results are not deterministic. I have tested with the same text in the [demo uniNER](https://universal-ner.github.io) and here it works.

How could we set it deterministic?

Here is my code

```
>>> prompt = 'A virtual assistant answers questions from a user based on the provided text.\nUSER: Text: D. Juan Pérez-Rodríguez López, procurador de los Tribunales y de LUMINA FINANCIERA FICTICIA S.A. (en adelante, “LUMINA”), según consta acreditado en autos, bajo la dirección letrada de Carlos Montesinos Ramírez, colegiado núm. 65.432 del Ilustre Colegio de Abogados de Barcelona (ICAB), ante el Juzgado y como mejor proceda en Derecho, DIGO.\nASSISTANT: I’ve read this text.\nUSER: What describes company name in the text?\nASSISTANT:'

>>> pipeline(prompt)
[{'generated_text': 'A virtual assistant answers questions from a user based on the provided text.\nUSER: Text: D. Juan Pérez-Rodríguez López, procurador de los Tribunales y de LUMINA FINANCIERA FICTICIA S.A. (en adelante, “LUMINA”), según consta acreditado en autos, bajo la dirección letrada de Carlos Montesinos Ramírez, colegiado núm. 65.432 del Ilustre Colegio de Abogados de Barcelona (ICAB), ante el Juzgado y como mejor proceda en Derecho, DIGO.\nASSISTANT: I’ve read this text.\nUSER: What describes company name in the text?\nASSISTANT: []'}]

>>> pipeline(prompt)
[{'generated_text': 'A virtual assistant answers questions from a user based on the provided text.\nUSER: Text: D. Juan Pérez-Rodríguez López, procurador de los Tribunales y de LUMINA FINANCIERA FICTICIA S.A. (en adelante, “LUMINA”), según consta acreditado en autos, bajo la dirección letrada de Carlos Montesinos Ramírez, colegiado núm. 65.432 del Ilustre Colegio de Abogados de Barcelona (ICAB), ante el Juzgado y como mejor proceda en Derecho, DIGO.\nASSISTANT: I’ve read this text.\nUSER: What describes company name in the text?\nASSISTANT: ["LUMINA FINANCIERA FICTICIA S.A."]'}]
```

The first time _LUMINA FINANCIERA FICTICIA S.A._ is not detected and the second time it is correctly detected.

**Comment by wzhouad** [comment]
I added a hf.py file under the src/serve directory for inferencing with huggingface transformers. It should generate deterministic outputs.
